apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sans-mercy-cert
  namespace: sans-mercy
spec:
  # Secret names are always required.
  secretName: sans-mercy-tls-auto
  dnsNames: 
    - sansmercy.com
  issuerRef:
    name: letsencrypt-issuer
    kind: Issuer
