apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: main-rev-prox
  namespace: archie
  annotations:
    cert-manager.io/issuer: "letsencrypt-issuer"
spec:
  entryPoints:
    - websecure
  tls:
    secretName: archie-tls-auto
  routes:
  - kind: Rule
    match: Host(`archie.zapto.org`) && PathPrefix(`/jf-lh`)
    services:
    - kind: Service 
      name: jellyfin-longhorn
      namespace: archie
      port: 1997
  - kind: Rule
    match: Host(`archie.zapto.org`) && PathPrefix(`/jellyfin`)
    services:
    - kind: Service 
      name: jellyfin
      namespace: archie
      port: 8096
  - kind: Rule
    match: Host(`archie.zapto.org`) #&& PathPrefix(`/`)
    services:
    - kind: Service
      name: archie-svr
      namespace: archie
      port: 4949

