# PVC for the media
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-longhorn
  namespace: archie
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi


---

# PVC for the config/metadata volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cfg-longhorn
  namespace: archie
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
