apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-ui-cert
  namespace: longhorn-system
spec:
  # Secret names are always required.
  secretName: longhorn-tls-auto
  dnsNames: 
    - archie.zapto.org
  issuerRef:
    name: letsencrypt-issuer
    kind: Issuer
